

obj-$(CONFIG_PLATFORM_STM32F429) += mcu.c
obj-$(CONFIG_PLATFORM_STM32F429) += stm32f4xx_it.c
obj-$(CONFIG_PLATFORM_STM32F429) += stm32f4xx_hal_msp.c
obj-$(CONFIG_PLATFORM_STM32F429) += sysmem.c
obj-$(CONFIG_PLATFORM_STM32F429) += syscalls.c
obj-$(CONFIG_PLATFORM_STM32F429) += system_stm32f4xx.c

# STM32 HAL drivers (always enabled for STM32F429)
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c
obj-$(CONFIG_PLATFORM_STM32F429) += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c